[build]
builder = "nixpacks"

[phases.setup]
cmds = [
  "apt-get update",
  "apt-get install -y --no-install-recommends build-essential python3-dev",
  "apt-get install -y --no-install-recommends libffi-dev libblas-dev liblapack-dev",
  "apt-get install -y --no-install-recommends libmagic1 libxml2-dev libxslt1-dev"
]

[phases.install]
cmds = ["pip install --no-cache-dir -r requirements.txt"]

[start]
cmd = "uvicorn main:app --host 0.0.0.0 --port $PORT"
